### ISSUE TITLE
Error running node ./examples/voice-sdk/realtime-websocket-single-stream/index.js

### ISSUE THREAD

**Issue by Emelieh21** [symblai/getting-started-samples#16]
Hi guys,

I was curious to try out the realtime websocket single stream example of this repo. I followed the steps and added my credentials, but kept running into the following error:

```
(node:10632) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
(Use `node --trace-warnings ...` to show where the warning was created)

Successfully connected. Conversation ID:  6636XXXXXXXX3040
Started listening to Microphone.
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: spawn rec ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn rec',
  path: 'rec',
  spawnargs: [
    '-b',       '16',
    '--endian', 'little',
    '-c',       '1',
    '-r',       16000,
    '-e',       'signed-integer',
    '-t',       'raw',
    '-'
  ]
}
``` 
Any idea what could be causing this issue and how I could fix it? I am running this on Mac. I tried clearing my npm cache and reinstalling everything, but no success.

Cheers and have a nice evening,

Emelie

**Comment by eric-giannini** [comment]
Hey, @Emelieh21! Thanks for reaching out. Our team is currently looking into the issue. We'll ping you asap. In the meantime please reach out to me directly on [Slack](https://join.slack.com/t/symbldotai/shared_invite/zt-4sic2s11-D3x496pll8UHSJ89cm78CA) to discuss workarounds for your use-case.

**Comment by avoliva** [comment]
Hello @Emelieh21 

Sorry you had an issue with this project. I believe this is because you need to install `sox`. You can install `sox` on Mac using `brew install sox`. I'll update the README.md to include this piece. In the meantime, you can refer to [this tutorial](https://docs.symbl.ai/docs/javascript-sdk/guides/push-audio-get-realtime-data), which has a more in-depth explanation of this example program.

**Comment by eric-giannini** [comment]
@Emelieh21 Our team reviewed the issue! Please let us know, if you run into any further errors! Feel free to comment here or reach out to me directly on [Slack](https://join.slack.com/t/symbldotai/shared_invite/zt-4sic2s11-D3x496pll8UHSJ89cm78CA) for any more questions! Thanks!

**Comment by Emelieh21** [comment]
Thanks a lot for the fast reply! I can confirm that after running `brew install sox` it works! Really cool :) Thanks so much.
